### PR TITLE
Update clean-css to latest version

### PR DESCRIPTION
**Pull request by weaintplastic**
I've updated the clean-css dependency to version 4.* since it is using a newer version of source-map which is compatible with webpack 2. Currently oy is not working with webpack 2 due to some dynamic requires in source-map.

* Update package.json dependecy
* Update Render.js since `minify()` of version 4 can't handle `undefined`
* Remove CSS unsafe check for closing style tag since clean-css takes care of it in the new version. It returns empty styles plus a warning in the result of minify. 
* Remove tests for closing style tag

### CODE REVIEW

**Comment by weaintplastic** [comment]
Hi, do you have any thoughts on this change?

**Comment by weaintplastic** [comment]
@revivek Do you have any thoughts on this? Would love to hear your feedback.

**Comment by revivek** [comment]
Sorry for the delay—I've been traveling for the last 3 weeks and just got back. Will try to review this weekend.

**Comment by weaintplastic** [comment]
Thanks a lot @revivek

**Comment by revivek** [comment]
Thanks, this looks good to me! Interesting that webpack is a use-case here. I've only ever used webpack for bundling assets, though I suppose there's nothing holding it back from being used for backends too. Once you resolve the conflicts, I'll merge.

**Comment by weaintplastic** [comment]
@revivek Thanks a lot for reviewing. Addressed the conflicts and should be good to go now.

**Comment by revivek** [comment]
Word.

**Pull request merged**
