### PR TITLE
Document details about custom template functionality

### PR DESCRIPTION
**Pull request by yuindustries**
Hi @revivek,

I created this PR to add some more details about how to implement custom templates. I was really struggling to figure out how to use the feature. So I wrote down some notes that would have been helpful to myself.

I really appreciate you creating and maintaining this project. I was feeling daunted by the task of generating a bunch of branded HTML emails, but overall Oy has made it much more pleasant!

### CODE REVIEW

**Comment by Rendez** [comment]
@yuindustries great contribution IMO. However, I think it could be made a bit more concise, since the concept you're explaining is relatively easy to grasp ;)

**Comment by yuindustries** [comment]
Thanks, @Rendez. Yes, I was a bit concerned that it was verbose compared to the rest of the README, so I defer to the project maintainer. Use or edit as needed.

That said, I hope my notes are useful insight for someone like you (who had no trouble grasping the concept as documented) to learn more about someone like me (who didn't grasp the concept, and even found the documentation misleading). 

Sometimes, when you're deeply familiar with a concept, it can actually make it harder for you to explain it clearly.

**Comment by revivek** [comment]
Appreciate the contribution, @yuindustries. Happy to add a few more details for using custom templates. As is hopefully obvious, I'm hoping to keep the usage docs digestible via a single README. I left a few comments to that end.

**Comment by yuindustries** [comment]
Thanks, @revivek! I looked around for your comments in this PR, but I didn't see any others besides the note you just wrote. Did I miss something?

As a way of making my edits more concise, I hid the code samples in a `<details>` tag. That way the information is still available, but without adding to the perceived length of your README. 

What do you think?

**Comment by revivek** [comment]
Sorry, I forgot to officially "start" the review! You should be able to see my comments now. With some edits, I don't think we'll need to use the `<details>` tag.

**Comment by yuindustries** [comment]
Hi @revivek — Thank you for the thoughtful and detailed feedback! I made the suggested edits. What do you think of this latest version?

**Comment by revivek** [comment]
Looks great! Merging.

**Pull request merged**
